services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: alamakota
      POSTGRES_USER: board_games
      POSTGRES_DB: games
    ports:
      - 5432:5432

  backend:
    build:
      context: ./back-end/
      dockerfile: ./back-end/Dockerfile
    ports:
      - 5000:5000
    env_file:
      - path: ./back-end/.env
        required: true
    depends_on:
      - postgres

  frontend:
    build:
      context: ./front-end/
      dockerfile: ./front-end/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - path: ./front-end/.env
        required: true
    depends_on:
      - backend
