apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-deployment
  namespace: lazorko-czekalski
  labels:
    app: back-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-end
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
      - name: back-end
        image: ghcr.io/adamuspl/wiuda-back-end:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
          - secretRef:
              name: postgres-secret
          - secretRef:
              name: back-end-secret
        # - containerPort: ${{ vars.BACKEND_PORT }}
      imagePullSecrets:
      - name: ghcr-creds
---
apiVersion: v1
kind: Service
metadata:
  name: back-end-service
spec:
  type: NodePort
  selector:
    app: back-end
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
