name: Build and Push Docker Image

on:
  push:
    branches: [ docker ]
  pull_request:
    branches: [ docker ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          echo "gh_repo_owner_lc=${GITHUB_REPOSITORY_OWNER,,}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV
          IMAGE_NAME=ghcr.io/${{ env.gh_repo_owner_lc }}/python-app
          TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$TAG .
          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ env.gh_repo_owner_lc }}/python-app
          TAG=${{ github.sha }}
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
